sudo: false
language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
addons:
    postgresql: "9.4"
services:
    - postgresql
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY="SecretKeyForTravisCI"
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
        - AZUREAD_AUTHORITY="https://login.microsoftonline.com/thisisnotarealazureaudauthorityurl"
sudo: true
install:
    - sudo apt-get install postgresql-9.4-postgis-2.3 postgis -y -q
    - psql -U postgres -c "create extension postgis;"
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
before_script:
    - psql -U postgres -c 'create database travis_ci_test;'
    - python manage.py migrate --noinput
script:
    - coverage run --source="." manage.py test
after_success:
    - coveralls
